### ISSUE TITLE
Execute the "heat and trees" Panel example using Binder

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/dem-dashboard#1]
Execute [this heat and trees](https://github.com/jsignell/heat_and_trees) Panel dashboard example using Binder.

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge did you successfully run these notebooks using the Binder link?

**Comment by nicholaskgeorge** [comment]
@rsignell-usgs I didn't see this sorry. Yes I did and I used it as a reference. Very helpful!
