### ISSUE TITLE
Gitter Channel

### ISSUE THREAD

**Issue by nicholaskgeorge** [USGS-CMG/dem-dashboard#4]
The Gitter channel needs to be setup to allow us to communicate effectively

**Comment by dnowacki-usgs** [comment]
Thanks Nicholas! The channel has been set up at https://gitter.im/USGS-CMG/dem-dashboard

I assigned pull request #3 to you to add the Gitter badge to the README.md. This will be a good intro to getting acquainted with Markdown.
