### ISSUE TITLE
Bucket location for DEM data

### ISSUE THREAD

**Issue by nicholaskgeorge** [USGS-CMG/dem-dashboard#5]
The exact location and method of accessing the COG data needs to be provided in order to move forward.

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge , the DEM data we are ultimately interested in is a collection of Cloud-Optimized GeoTIFF data stored in this Amazon Bucket:  http://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Elevation/1/TIFF/

Which can be accessed via URLs like: 
https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1/TIFF/n36w109/USGS_1_n36w109.tif

But as a first step, see if you can figure out how to run this Notebook on the IceSat2 Pangeo: https://nbviewer.jupyter.org/gist/rsignell-usgs/31ead5112822c7245a87cc9ddc2667a5
