### ISSUE TITLE
Provide access to jupyterhub server

### ISSUE THREAD

**Issue by nicholaskgeorge** [USGS-CMG/dem-dashboard#6]
The **account** that will allow us to construct the dashboard and interact with the data must be **created**. Possibly setup a binder link.

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge , you should have an invite in you inbox to join the Pangeo github organization.
Once you accept it, you should be able to login to the AWS region us-west-2 Pangeo JupyterHub (limited to Pangeo members).

https://aws-uswest2.pangeo.io/hub/login

please let me know if this works!

**Comment by nicholaskgeorge** [comment]
Dear Mr. Signell,

I don't seem to have an invite request in my inbox and when I just tried to
log into the Pangeo github it didn't work. Could you send the invite
again please?

Thank you,

Nicholas

**Comment by rsignell-usgs** [comment]
@nganju-usgs , when you login to the [Pangeo endpoint](https://aws-uswest2.pangeo.io), you will usually want to select the "Latest Pangeo-notebook" image, as this is where the latest packages are (which we typically want!): 
![2020-07-13_12-02-40](https://user-images.githubusercontent.com/1872600/87326759-2c792f00-c501-11ea-9d48-f66de5f26f37.png)
