### ISSUE TITLE
Determine AWS region for DEM data bucket

### ISSUE THREAD

**Issue by nicholaskgeorge** [USGS-CMG/dem-dashboard#7]
@rsignell-usgs You said we needed to deal with this during the meeting.

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge right!   I'm hoping it is in region `us-west-2`, because that where the USGS Pangeo and IceSat2 Pangeo (the one you are using) are located!

**Comment by rsignell-usgs** [comment]
Here's the answer, using the method in https://stackoverflow.com/a/62997055/2005869

curl --head https://prd-tnm.s3.amazonaws.com
HTTP/1.1 200 OK
x-amz-id-2: fVZFQDPuA92slooVG8yKOd7OPrb2dUTFDegpGha9Jm3VCZtekC76XjJlfsehKHdLENLrNt/byG8=
x-amz-request-id: 31E4CABBD53368C2
Date: Tue, 21 Jul 2020 15:25:54 GMT
x-amz-bucket-region: us-west-2
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3
