### ISSUE TITLE
Create a persistent custom conda environment

### ISSUE THREAD

**Issue by nicholaskgeorge** [USGS-CMG/dem-dashboard#8]

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge, try following the approach here: https://github.com/ESIPFed/esiphub-dev/issues/27

**Comment by rsignell-usgs** [comment]
@nicholaskgeorge, does closing this issue mean you got a custom env going?  
(It's good practice to comment on why you are closing an issue, unless there is a PR which closes it)

**Comment by nicholaskgeorge** [comment]
The custom environment was created
